apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: random-pets
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - name: random-pets
          image: asia-northeast1-docker.pkg.dev/qwiklabs-gcp-04-36a6790654a7/app-repo/random-pets
          ports:
          - containerPort: 5000